apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash-data
  namespace: stash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 400Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: stash
  namespace: stash
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi