apiVersion: apps/v1
kind: Deployment
metadata:
  name: sftp
spec:
  selector:
    matchLabels:
      app: sftp
  template:
    metadata:
      labels:
        app: sftp
    spec:
      containers:
        - name: atmoz
          image: atmoz/sftp
          resources:
            requests:
              memory: 128Mi
              cpu: 200m
            limits:
              memory: 256Mi
              cpu: 500m
          ports:
            - containerPort: 22
          volumeMounts:
            - name: stash-data
              mountPath: /home/ray/
            - name: stash-sftp
              mountPath: /etc/sftp/users.conf
              subPath: users.conf
      volumes:
        - name: stash-data
          persistentVolumeClaim:
            claimName: stash-data
        - name: stash-sftp
          secret:
            secretName: stash-sftp