apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: stash-sftp
  namespace: stash
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secrets-manager
    kind: ClusterSecretStore
  target:
    name: stash-sftp
    creationPolicy:  Owner
  data:
    - secretKey: users.conf
      remoteRef:
        key: stash-sftp
        property: users.conf