apiVersion: v1
kind: Service
metadata:
  name: sftp
  namespace: stash
spec:
  type: ClusterIP
  ports:
    - name: ssh
      protocol: TCP
      port: 22
      targetPort: 22
      nodePort: 30022
  selector:
      app: sftp